apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-app
  name: nodejs-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nodejs-app
  strategy: {}
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
	  imagePullSecrets:
	  - name: docker-key
      containers:
      - image: 647833373684.dkr.ecr.ap-southeast-1.amazonaws.com/nodejs-test:latest
        name: nodejs-test
		ports:
		- containerPort: 3000
        resources:
          limits:
            cpu: 400m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
