apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority-nonpreemptive
value: 10000000
preemptionPolicy: Never
globalDefault: false
description: "This is a high priority class but will not cause other low priority pods to be preempted."
