---
kind: Service
apiVersion: v1
metadata:
  name: nodejs-app
spec:
  type: LoadBalancer
  selector:
    app: nodejs-app
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
